---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# 2021-SER

## Título
Coleta de dados automatizada e integração contínua utilizando GitHub Actions: Exemplos com o Pacote Mananciais

## Resumo

O GitHub Actions (GHA) (https://docs.github.com/pt/actions) permite automatizar fluxos de trabalho de desenvolvimento de pacotes em R. Nessa palestra, será mostrado alguns exemplos de uso de GitHub Actions no pacote Mananciais, que disponibiliza dados sobre o volume operacional em reservatórios utilizados para abastecimento público na Região Metropolitana de São Paulo. Os exemplos que utilizam GHA são: atualização da base de dados, checagem do pacote, execução de testes e avaliação da cobertura de testes. O pacote foi desenvolvido por Beatriz Milz, e pode ser acessado em: https://beatrizmilz.github.io/mananciais/index.html . Este pacote foi pensado para atender demandas de pessoas pesquisadoras que não somente utilizam R, disponibilizando também a base de dados atualizada diariamente em csv e em xlsx. 